name: "Vowel Frequency Analyzer"
description: "Custom Docker action to analyze vowel frequency in data.txt"

inputs:
  file:
    description: "The path to the text file to analyze"
    required: true
    default: "data.txt"

runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/app/.github/scripts/entrypoint.sh"
  env:
    FILE: ${{ inputs.file }}